---
permalink: api-automation/concept_metrics_apis.html 
sidebar: sidebar 
keywords: view, performance, metrics 
summary: Active IQ Unified Manager には、データセンターカテゴリ下の一連の API が用意されており、データセンター内のクラスタおよびストレージオブジェクトのパフォーマンスデータを表示できます。これらの API は、クラスタ、ノード、 LUN 、ボリュームなどのさまざまなストレージオブジェクトのパフォーマンスデータを取得します。 アグリゲート、 Storage VM 
---
= APIを使用したパフォーマンス指標の表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager には、の一連のAPIが用意されています `/datacenter` データセンター内のクラスタおよびストレージオブジェクトのパフォーマンスデータを表示できるカテゴリ。これらの API は、クラスタ、ノード、 LUN 、ボリューム、アグリゲートなどのさまざまなストレージオブジェクトのパフォーマンスデータを取得します。 Storage VM 、 FC インターフェイス、 FC ポート、イーサネットポート、 IP インターフェイス

。 `/metrics` および `/analytics` APIを使用すると、パフォーマンス指標をさまざまなビューで確認できます。データセンター内の次のストレージオブジェクトについて、さまざまなレベルの詳細にドリルダウンできます。

* クラスタ
* ノード
* Storage VMs
* アグリゲート
* 個のボリューム
* LUN
* FCインターフェイス
* FCポート
* イーサネットポート
* IP インターフェイス


次の表は、間の比較を示しています `/metrics` および `/analytics` 取得したパフォーマンスデータの詳細を示すAPI。

[cols="2*"]
|===
| 指標 | 分析 


 a| 
1 つのオブジェクトのパフォーマンスの詳細。たとえば、などです `/datacenter/cluster/clusters/\{key}/metrics` APIでは、特定のクラスタの指標を取得するためのパスパラメータとしてクラスタキーを入力する必要があります。
 a| 
データセンター内の同じタイプの複数のオブジェクトのパフォーマンスの詳細。たとえば、などです `/datacenter/cluster/clusters/analytics` APIは、データセンター内のすべてのクラスタの集合的な指標を取得します。



 a| 
読み出しの時間間隔パラメータに基づくストレージオブジェクトのパフォーマンス指標サンプル。
 a| 
特定の期間（ 72 時間を超える）における特定のタイプのストレージオブジェクトのパフォーマンスの概要レベルの集計値。



 a| 
ノードやクラスタの詳細など、オブジェクトの基本的な詳細が読み出されます。
 a| 
具体的な詳細は取得されません。



 a| 
1 つのオブジェクトについて、読み取り、書き込み、合計、その他のカウンタなど、一定期間の平均パフォーマンス値の最小値、最大値、 95 パーセンタイル値などの累積カウンタが取得されます。
 a| 
同じタイプのすべてのオブジェクトについて、集約された単一の値が表示されます。



 a| 
時間範囲とサンプルデータは、次のスケジュールに基づいています。データの時間範囲。例として、 1h 、 12h 、 1d 、 2d 、 3d があります。 15D 、 1w 、 1m 、 2m 、 3m 、 6M 。範囲が 3 日（ 72 時間）を超える場合は 1 時間のサンプルを取得し、それ以外の場合は 5 分のサンプルを取得します。各期間は次のとおりです。

* 1H ：直近 1 時間の測定値が 5 分以上にわたってサンプリングされます。
* 12 時間： 5 分以上にわたってサンプリングされた最新の 12 時間のメトリック。
* 1D ：直近の 1 日の測定値が 5 分以上にわたってサンプリングされます。
* 2D ：直近 2 日間の測定値が 5 分を超えてサンプリングされます。
* 3D ：直近 3 日間の測定値が 5 分を超えてサンプリングされます。
* 15D ： 1 時間にわたってサンプリングされた最新の 15 日間のメトリック。
* 1W ： 1 時間以上サンプリングされた最新の週のメトリック。
* 1M ：最近 1 時間でサンプリングされた月のメトリックス。
* 2M ：直近 2 カ月間の測定値が 1 時間以上にわたってサンプリングされます。
* 3M ：最近 3 カ月間の測定値が 1 時間以上サンプリングされています。
* 6M ：直近 6 カ月間の測定値が 1 時間以上にわたってサンプリングされます。
+
使用可能な値は、 1h 、 12h 、 1d 、 2d 、 3d です。 15D 、 1w 、 1m 、 2m 、 3m 、 6M

+
デフォルト値： 1h


 a| 
72 時間以上。このサンプルを計算する期間は、 ISO-8601 標準形式で表されます。

|===


== 指標APIの出力例

たとえば、などです `/datacenter/cluster/nodes/\{key}/metrics` APIがノードについて次の詳細を取得する（特にその他）。


NOTE: サマリ値の 95 パーセンタイルは、期間について収集されたサンプルの 95% が、 95 パーセンタイルで指定された値よりも小さいカウンタ値を持っていることを示しています。

[listing]
----
{
     "iops": {
       "local": {
         "other": 100.53,
         "read": 100.53,
         "total": 100.53,
         "write": 100.53
       },
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "latency": {
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "performance_capacity": {
       "available_iops_percent": 0,
       "free_percent": 0,
       "system_workload_percent": 0,
       "used_percent": 0,
       "user_workload_percent": 0
     },
     "throughput": {
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "timestamp": "2018-01-01T12:00:00-04:00",
     "utilization_percent": 0
   }
 ],
 "start_time": "2018-01-01T12:00:00-04:00",
 "summary": {
   "iops": {
     "local_iops": {
       "other": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "read": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "total": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "write": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       }
     },
----


== 分析APIの出力例を示します

たとえば、などです `/datacenter/cluster/nodes/analytics` APIがすべてのノードに対して次の値を（特に）取得する。

[listing]
----
{     "iops": 1.7471,
     "latency": 60.0933,
     "throughput": 5548.4678,
     "utilization_percent": 4.8569,
     "period": 72,
     "performance_capacity": {
       "used_percent": 5.475,
       "available_iops_percent": 168350
     },
     "node": {
       "key": "37387241-8b57-11e9-8974-00a098e0219a:type=cluster_node,uuid=95f94e8d-8b4e-11e9-8974-00a098e0219a",
       "uuid": "95f94e8d-8b4e-11e9-8974-00a098e0219a",
       "name": "ocum-infinity-01",
       "_links": {
         "self": {
           "href": "/api/datacenter/cluster/nodes/37387241-8b57-11e9-8974-00a098e0219a:type=cluster_node,uuid=95f94e8d-8b4e-11e9-8974-00a098e0219a"
         }
       }
     },
     "cluster": {
       "key": "37387241-8b57-11e9-8974-00a098e0219a:type=cluster,uuid=37387241-8b57-11e9-8974-00a098e0219a",
       "uuid": "37387241-8b57-11e9-8974-00a098e0219a",
       "name": "ocum-infinity",
       "_links": {
         "self": {
           "href": "/api/datacenter/cluster/clusters/37387241-8b57-11e9-8974-00a098e0219a:type=cluster,uuid=37387241-8b57-11e9-8974-00a098e0219a"
         },
     "_links": {
       "self": {
         "href": "/api/datacenter/cluster/nodes/analytics"
       }
     }
   },
----


== 使用可能なAPIのリスト

次の表で、について説明します `/metrics` および `/analytics` APIの詳細をご覧ください。

[NOTE]
====
これらのAPIから返されるIOPSとパフォーマンスの指標には、たとえば2倍の値があります `100.53`。これらの浮動小数点値をパイプ（ | ）およびワイルドカード（ * ）文字でフィルタリングすることはできません。

====
[cols="3*"]
|===
| HTTP 動詞 | パス | 説明 


 a| 
`GET`
 a| 
`/datacenter/cluster/clusters/\{key}/metrics`
 a| 
クラスタキーの入力パラメータで指定したクラスタのパフォーマンスデータ（サンプルと概要）を取得します。クラスタキーと UUID 、時間範囲、 IOPS 、スループット、サンプル数などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/cluster/clusters/analytics`
 a| 
は、データセンター内のすべてのクラスタのパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタできます。集計 IOPS 、スループット、収集期間（時間数）などの値が返されます。



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes/\{key}/metrics`
 a| 
ノードキーの入力パラメータで指定したノードのパフォーマンスデータ（サンプルとサマリ）を取得します。ノード UUID 、時間範囲、 IOPS 、スループット、レイテンシ、パフォーマンスの概要、収集されたサンプル数、利用率などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes/analytics`
 a| 
は、データセンター内のすべてのノードのパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタできます。ノードキーやクラスタキーなどの情報、および集計 IOPS 、スループット、収集期間（時間数）などの値が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates/\{key}/metrics`
 a| 
aggregate キーの入力パラメータで指定したアグリゲートのパフォーマンスデータ（サンプルとサマリ）を取得します。時間範囲、 IOPS 、レイテンシ、スループット、パフォーマンス容量の概要、各カウンタで収集されたサンプル数、使用率などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates/analytics`
 a| 
データセンター内のすべてのアグリゲートのパフォーマンス指標の概要が取得されます。必要な条件に基づいて結果をフィルタできます。アグリゲートキーやクラスタキーなどの情報、および集計 IOPS 、スループット、収集期間（時間数）などの値が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/luns/\{key}/metrics`

`/datacenter/storage/volumes/\{key}/metrics`
 a| 
LUN またはボリュームキーの入力パラメータで指定された LUN またはファイル共有（ボリューム）のパフォーマンスデータ（サンプルとサマリ）を取得します。読み取り、書き込み、合計 IOPS 、レイテンシ、スループットの最小値、最大値、平均値の概要などの情報。 各カウンタについて収集されたサンプル数が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/luns/analytics`

`/datacenter/storage/volumes/analytics`
 a| 
データセンター内のすべての LUN またはボリュームのパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタできます。Storage VM やクラスタキーなどの情報、および集計 IOPS 、スループット、収集期間（時間数）などの値が返されます。



 a| 
`GET`
 a| 
`/datacenter/svm/svms/{key}/metrics`
 a| 
Storage VM キーの入力パラメータで指定した Storage VM のパフォーマンスデータ（サンプルと概要）を取得します。など、サポートされている各プロトコルに基づくIOPSの概要 `nvmf, fcp, iscsi,` および `nfs`、スループット、レイテンシ、収集されたサンプル数が返されます。



 a| 
`GET`
 a| 
`/datacenter/svm/svms/analytics`
 a| 
は、データセンター内のすべての Storage VM のパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタできます。Storage VM の UUID 、アグリゲート IOPS 、レイテンシ、スループット、収集期間（時間数）などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/network/ethernet/ports/{key}/metrics`
 a| 
ポートキーの入力パラメータで指定された特定のイーサネットポートのパフォーマンス指標を取得します。サポートされている範囲から間隔（時間範囲）を指定すると、 API はその期間における最小、最大、平均パフォーマンス値などの累積カウンタを返します。



 a| 
`GET`
 a| 
`/datacenter/network/ethernet/ports/analytics`
 a| 
データセンター環境内のすべてのイーサネットポートのパフォーマンス指標の概要を取得します。クラスタとノードキー、 UUID 、スループット、収集期間、ポートの利用率などの情報が返されます。ポートキー、利用率、クラスタとノードの名前と UUID など、使用可能なパラメータで結果をフィルタリングできます。



 a| 
`GET`
 a| 
`/datacenter/network/fc/interfaces/{key}/metrics`
 a| 
インターフェイスキーの入力パラメータで指定した特定のネットワーク FC インターフェイスのパフォーマンス指標を取得します。サポートされている範囲から間隔（時間範囲）を指定すると、 API はその期間における最小、最大、平均パフォーマンス値などの累積カウンタを返します。



 a| 
`GET`
 a| 
`/datacenter/network/fc/interfaces/analytics`
 a| 
データセンター環境内のすべてのイーサネットポートのパフォーマンス指標の概要を取得します。クラスタと FC インターフェイスキーと UUID 、スループット、 IOPS 、レイテンシ、 Storage VM などの情報が返されます。クラスタと FC インターフェイスの名前と UUID 、 Storage VM 、スループットなど、使用可能なパラメータで結果をフィルタリングできます。



 a| 
`GET`
 a| 
`/datacenter/network/fc/ports/{key}/metrics`
 a| 
ポートキーの入力パラメータで指定した特定の FC ポートのパフォーマンス指標を取得します。サポートされている範囲から間隔（時間範囲）を指定すると、 API はその期間における最小、最大、平均パフォーマンス値などの累積カウンタを返します。



 a| 
`GET`
 a| 
`/datacenter/network/fc/ports/analytics`
 a| 
データセンター環境内のすべての FC ポートのパフォーマンス指標の概要を取得します。クラスタとノードキー、 UUID 、スループット、収集期間、ポートの利用率などの情報が返されます。ポートキー、利用率、クラスタとノードの名前と UUID など、使用可能なパラメータで結果をフィルタリングできます。



 a| 
`GET`
 a| 
`/datacenter/network/ip/interfaces/{key}/metrics`
 a| 
インターフェイスキーの入力パラメータで指定されたネットワーク IP インターフェイスのパフォーマンス指標を取得します。サポートされている範囲から間隔（時間範囲）を指定すると、サンプル数、累積カウンタ、スループット、送受信パケット数などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/network/ip/interfaces/analytics`
 a| 
データセンター環境内のすべてのネットワーク IP インターフェイスのパフォーマンス指標の概要を取得します。クラスタと IP インターフェイスキー、 UUID 、スループット、 IOPS 、レイテンシなどの情報が返されます。クラスタと IP インターフェイスの名前と UUID 、 IOPS 、レイテンシ、スループットなど、使用可能なパラメータで結果をフィルタリングできます。

|===