---
permalink: install-linux/task_install_unified_manager_linux.html 
sidebar: sidebar 
keywords: install, unified manager 
summary: Unified Manager は、 Red Hat Enterprise Linux または CentOS の物理プラットフォームまたは仮想プラットフォームにインストールできます。 
---
= Unified Manager をインストールしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager は、 Red Hat Enterprise Linux または CentOS の物理プラットフォームまたは仮想プラットフォームにインストールできます。

* 必要なもの *

* Unified Manager をインストールするシステムがシステムおよびソフトウェアの要件を満たしている必要があります。
+
を参照してください link:concept_virtual_infrastructure_or_hardware_system_requirements.html["ハードウェアシステムの要件"]。

+
を参照してください link:reference_red_hat_and_centos_software_and_installation_requirements.html["Linux ソフトウェアとインストールの要件"]。

* Unified Managerをダウンロードしておく必要があります `.zip` ファイルをNetApp Support Site からターゲットシステムにコピーします。
* ダウンロードしたの整合性を確認しておく必要があります `.zip` ファイル。
* サポートされている Web ブラウザが必要です。
* ターミナルエミュレーションソフトウェアでスクロールバックが有効になっている必要があります。


Red Hat Enterprise Linux または CentOS のシステムには、必要なサポートソフトウェア（ Java 、 MySQL 、追加ユーティリティ）のすべてのバージョンがインストールされているか、必要なソフトウェアの一部のみがインストールされているか、または新たにインストールしたシステムに必要なソフトウェアがインストールされていない可能性があります。

.手順
. Unified Manager をインストールするサーバにログインします。
. 該当するコマンドを入力し、インストールをサポートするためにターゲットシステムでインストールまたはアップグレードが必要なソフトウェアを特定します。
+
[cols="2*"]
|===
| 必要なソフトウェアと最小バージョン | ソフトウェアとバージョンを確認するコマンド 


 a| 
OpenJDKバージョン11.0.17
 a| 
`java -version`



 a| 
MySQL 8.0.32 Community Edition
 a| 
`rpm -qa | grep -i mysql`



 a| 
p7zip 16.02
 a| 
`rpm -qa | grep p7zip`

|===
. MySQL 8.0.32 Community Editionより前のバージョンのMySQLがインストールされている場合は、次のコマンドを入力してアンインストールします。
+
`rpm -e <mysql_package_name>`

+
依存関係のエラーが表示された場合は、を追加する必要があります `--nodeps` コンポーネントをアンインストールするオプション。

. インストールをダウンロードしたディレクトリに移動します `.zip` Unified Managerのバンドルをファイルして展開します。
+
`unzip ActiveIQUnifiedManager-_<version>_.zip`

+
が必要です `.rpm` Unified Managerのモジュールがターゲットディレクトリに解凍されます。

. ディレクトリに次のモジュールがあることを確認します。
+
`ls *.rpm`

+
`netapp-um<version>.x86_64.rpm`

. インストール前スクリプトを実行して、 Unified Manager のインストールと競合するシステム設定やインストール済みソフトウェアがないことを確認します。
+
`sudo ./pre_install_check.sh`

+
インストール前スクリプトは、システムに有効なRed Hat Enterprise Linuxサブスクリプションがあるかどうか、およびシステムが必要なソフトウェアリポジトリにアクセスできるかどうかを確認します。問題が検出された場合は、 Unified Manager をインストールする前に修正する必要があります。

+
Red Hat Enterprise Linux 8 システムの場合、 JDK 11-OpenJDK 、 p7zip 、その他の AppStream リポジトリが提供するソフトウェアパッケージを使用した内部リポジトリがある場合、 AppStream リポジトリを無効にして MySQL Community Server をインストールする必要があります。次のコマンドを実行します。

+
[listing]
----
# sudo yum --disablerepo=rhel-8-for-x86_64-appstream-rpms install  mysql-community-server
----
. * オプション： * システムがインターネットに接続されておらず、インストールに必要なパッケージを手動でダウンロードする必要がある場合にのみ、手順 7 を実行する必要があります。インターネットにアクセスできるシステムで、必要なすべてのパッケージがある場合は、ステップ8に進みます。システムがインターネットに接続されていない場合やRed Hat Enterprise Linuxのリポジトリを使用していない場合は、次の手順に従って、必要なパッケージが揃っているかどうかを確認し、足りないパッケージをダウンロードします。
+
.. Unified Manager をインストールするシステムで、各パッケージについてその有無を表示します。
 [+]
`yum install netapp-um<version>.x86_64.rpm --assumeno`
+
"Installing :`" セクションの項目は現在のディレクトリにあるパッケージで、 "Installing for dependencies ： " セクションの項目はシステムにないパッケージです。

.. インターネットにアクセスできるシステムで、不足しているパッケージをダウンロードします。
+
`yum install <package_name> --downloadonly --downloaddir=.`

+
[NOTE]
====
プラグイン「 yum-plugin-downloadonly 」は、 Red Hat Enterprise Linux システムで常に有効になっているとは限りません。インストールせずにパッケージをダウンロードするには、この機能を有効にする必要があります。
`yum install yum-plugin-downloadonly`

====
.. インターネットに接続されたシステムから不足しているパッケージをインストールシステムにコピーします。


. をrootユーザとして使用するか、を使用します `sudo`を使用して、次のコマンドを実行してソフトウェアをインストールします。
+
`yum install netapp-um<version>.x86_64.rpm`

+
このコマンドを実行すると、 .rpm パッケージ、必要な他のすべてのサポートソフトウェア、および Unified Manager ソフトウェアがインストールされます。

+
インストールがGPG NOKEYエラーで失敗した場合は、を使用します `rpm --import` URLからキーをインポートするには、次の手順に従います。

+
`rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022`

+
[NOTE]
====
インストールの実行に他のコマンド（など）は使用しないでください `rpm -ivh`）。Unified ManagerをRed Hat Enterprise LinuxまたはCentOSのシステムに正しくインストールするには、Unified Managerのすべてのファイルと関連ファイルを特定の順序で特定のディレクトリ構造にインストールする必要があり、そのためにはによって自動的に適用されます `yum install netapp-um<version>.x86_64.rpm` コマンドを実行します

====
. インストールメッセージの直後に表示される E メール通知は無視してください。
+
この E メールは最初の cron ジョブの失敗を root ユーザに通知するもので、インストールには影響しません。

. インストールメッセージが最後まで表示されたら、メッセージを上にスクロールして、 Unified Manager Web UI の IP アドレスまたは URL 、メンテナンスユーザの名前（ umadmin ）、およびデフォルトのパスワードを確認します。
+
次のようなメッセージが表示されます。

+
[listing]
----
Active IQ Unified Manager installed successfully.
Use a web browser and one of the following URL(s) to configure and access the Unified Manager GUI.
https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/

Log in to Unified Manager in a web browser by using following details:
  username: umadmin
  password: admin
----
. IP アドレスまたは URL 、割り当てられたユーザ名（ umadmin ）、および現在のパスワードをメモします。
. Unified Manager をインストールする前にカスタムのホームディレクトリで umadmin ユーザアカウントを作成していた場合は、 umadmin ユーザのログインシェルを指定する必要があります。
+
`usermod -s /bin/maintenance-user-shell.sh umadmin`



の説明に従って、Web UIにアクセスしてumadminユーザのデフォルトパスワードを変更し、Unified Managerの初期セットアップを実行します link:../config/concept_configure_unified_manager.html["Active IQ Unified Manager を設定しています"]。umadminユーザのデフォルトパスワードを変更する必要があります。
